apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: turtl-postgres-pv-claim
  labels:
    app: turtl
spec:
  storageClassName: rook-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi